src/models/payment.py
from ..utils import db
from flask_login import UserMixin
from sqlalchemy.sql import func


class Payment(db.Model):
    """Payment model"""

    
    __tablename__ = 'payment'
    id = db.Column(db.Integer, primary_key = True)
    buyer_id = db.Column(db.Integer, nullable = False)
    seller_id = db.Column(db.Integer, nullable = False)
    product_id = db.Column(db.Integer, nullable = False)
    status = db.Column(db.String(50), nullable = False)
    payment_method = db.Column(db.String(50), nullable = False)
    transaction_id = db.Column(db.String(50), nullable = False)
    country_code = db.Column(db.String(50), nullable = False)
    gross_pay = db.Column(db.Integer, nullable = False)
    paypal_fee = db.Column(db.Integer)
    paypal_email = db.Column(db.String(250))
    payment_number = db.Column(db.String(15))
    mpesa_fee = db.Column(db.Integer)
    net_pay = db.Column(db.Integer)
    currency_paid = db.Column(db.String(80), nullable = False)
    transaction_date = db.Column(db.String(50), nullable = False)
    transaction_time = db.Column(db.String(50), nullable = False)
    date_modified = db.Column(db.DateTime(timezone = True), nullable=False, server_default=func.now(), onupdate=func.now())
    


    def __repr__(self):
        return '<Payment %r>' % self.payment_method

src/main/views.py
import os
import secrets
import requests
import json
from requests.auth import HTTPBasicAuth
import base64
import logging
from datetime import datetime
import PIL.Image
from flask import (Blueprint, redirect, render_template, request, flash, url_for, jsonify, current_app, abort, Response,
                   send_file)
from ..models.accounts import Account
from ..models.users import User
from ..models.notification import Notification
from ..models.complaints import Complaints
from ..models.images import Image
from ..models.confirmation import Confirmation
from ..models.account_credentials import Account_Credentials
from ..models.payment import Payment
from ..models.subscription_list import Subscription
from ..models.files import File
from ..auth.form_fields import (Seller_Profile_Form, Account_Images, Update_User_Account, Payment_Method, 
                                Complaint, Confirmation_Form, Seller_Account_Details, Search, FilteredSearch,
                                Mpesa_Confirm, Contact_Us, Order_By, Seller_Complete_Account_Details, Accept_Account,
                                Upload_Images, Purchase_Status, Conclude_Transaction, )
from ..utils import db, mail
from flask_login import login_user, logout_user, login_required, current_user
from sqlalchemy import and_, desc, asc
from datetime import date
from werkzeug.utils import secure_filename
from decouple import config
import phonenumbers
from sqlalchemy.exc import IntegrityError, PendingRollbackError
from flask_mail import Message 
from glob import glob
from io import BytesIO
from zipfile import ZipFile

# configure logging
logging.basicConfig(format='%(asctime)s:%(levelname)s:%(filename)s:%(funcName)s:%(message)s',
                    datefmt='%Y-%m-%d %H:%M:%S',
                    level=logging.INFO)


main = Blueprint('main', __name__)

# Custom Functions
def save_picture_thumbnail(form_picture):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(current_app.root_path, 'static/images/profile_pics', picture_fn)

    output_size = (125, 125)
    img = PIL.Image.open(form_picture)
    img.thumbnail(output_size)
    img.save(picture_path)

    return picture_fn

def save_pictures(form_picture):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(current_app.root_path, 'static/images/account_images', picture_fn)

    img = PIL.Image.open(form_picture)
    img.save(picture_path)

    return picture_fn

def save_files(form_file):
    if form_file:
        # generate random hashes as file name
        random_hex = secrets.token_hex(8)
        _, f_ext = os.path.splitext(form_file.filename)
        picture_fn = random_hex + f_ext
        picture_path = os.path.join(current_app.root_path, 'static/assets/files', picture_fn)
        form_file.save(picture_path)

        return picture_fn

def is_file_empty(file_path):
    """ Check if file is empty by confirming if its size is 0 bytes"""
    # Check if file exist and it is empty
    return os.path.exists(file_path) and os.stat(file_path).st_size == 0


@main.route('/search', methods = ['POST', 'GET'])
def search_results():
    search_form = Search()
    filter_form = FilteredSearch()
    purchase_form = Payment_Method()
    order_by_form = Order_By()
    page = request.args.get('page', 1, type=int)
    accounts = Account.query.filter_by(status = 0).paginate(page=page, per_page=10, error_out=False)

    if request.method == 'POST':

        if search_form.validate_on_submit():
            # get data from submitted form
            keyword = search_form.keyword.data
            print(keyword)
    
            # query the database
            searched_accounts = Account.query.filter(Account.description.like('%' + keyword + '%')).paginate(page=page, per_page=10, error_out=False)    
            return render_template('search.html', form = search_form, logged_in_user=current_user, keyword = keyword, account = searched_accounts, purchase_form = purchase_form, order = order_by_form, filter_form = filter_form)
        
    return render_template('search.html', form = search_form, logged_in_user=current_user, account = accounts, purchase_form = purchase_form, order = order_by_form, filter_form = filter_form)

@main.route('/about_us', methods = ['GET', 'POST'])
def about_us():
    return render_template('about_us.html')

@main.route('/', methods = ['GET', 'POST'])
def viewpage():
    page = request.args.get('page', 1, type=int)
    account = Account.query.filter_by(status = 0).paginate(page=page, per_page=10, error_out=False)
    search_form = Search()
    filter_form = FilteredSearch()
    purchase_form = Payment_Method()
    order_by_form = Order_By()

    if current_user.is_anonymous:
        notification = False

    if current_user.is_authenticated:
        buyer_msg = Notification.query.filter_by(buyer_id = current_user.id).first()
        seller_msg = Notification.query.filter_by(seller_id = current_user.id).first()

        #check if notifications exist
        notification = True if buyer_msg or seller_msg else False
    
   
    if request.method == 'POST':
        if purchase_form.validate_on_submit():
            account_id = purchase_form.info.data
            payment_method = purchase_form.payment_method.data
            account_seller = Account.query.filter_by(account_id = account_id).first()
            if payment_method == 'Mpesa':
                buyer_id = current_user.id
                seller_id = account_seller.user_id
                return redirect(url_for('main.mpesa_payment', payment_method = payment_method, product_id = account_id, buyer_id = buyer_id, seller_id = seller_id))
            elif payment_method == 'Paypal':
                buyer_id = current_user.id
                seller_id = account_seller.user_id
                return redirect(url_for('main.paypal_payment', payment_method = payment_method, product_id = account_id, buyer_id = buyer_id, seller_id = seller_id))
            else:
                return render_template('404.html'), 404

        elif order_by_form.validate_on_submit():
            order_item = order_by_form.account_type.data
            if order_item == "highest_price":
                account = Account.query.filter_by(status = 0).order_by(Account.price.desc()).paginate(page=page, per_page=10, error_out=False)
                return render_template('view.html', account=account, logged_in_user=current_user, purchase_form = purchase_form, form = search_form, order = order_by_form, filter_form = filter_form, notification = notification)
            elif order_item == "lowest_price":
                account = Account.query.filter_by(status = 0).order_by(Account.price.asc()).paginate(page=page, per_page=10, error_out=False)
                return render_template('view.html', account=account, logged_in_user=current_user, purchase_form = purchase_form, form = search_form, order = order_by_form, filter_form = filter_form, notification = notification)
            elif order_item == "date_posted_old":
                account = Account.query.filter_by(status = 0).order_by(Account.time_posted.asc()).paginate(page=page, per_page=10, error_out=False)
                return render_template('view.html', account=account, logged_in_user=current_user, purchase_form = purchase_form, form = search_form, order = order_by_form, filter_form = filter_form, notification = notification)
            elif order_item == "date_posted_new":
                account = Account.query.filter_by(status = 0).order_by(Account.time_posted.desc()).paginate(page=page, per_page=10, error_out=False)
                return render_template('view.html', account=account, logged_in_user=current_user, purchase_form = purchase_form, form = search_form, order = order_by_form, filter_form = filter_form, notification = notification)
            
            return render_template('view.html', account=account, logged_in_user=current_user, purchase_form = purchase_form, form = search_form, order = order_by_form, notification = notification)
        
        elif filter_form.validate_on_submit():
            article_ac = filter_form.article_ac.data
            academic_ac = filter_form.academic_ac.data
            blogging_ac = filter_form.blogging_ac.data
            price_range_a = filter_form.price_range_a.data
            price_range_b = filter_form.price_range_b.data

                
            if article_ac and academic_ac and blogging_ac and price_range_a and price_range_b:
                account_ = Account.query.filter_by(status = 0).filter((Account.account_type == "ARTICLE_ACCOUNT" and "BLOGGING_ACCOUNT" and "ACADEMIC_WRITING_ACCOUNT")).filter((Account.price >= price_range_a) & (Account.price <= price_range_b))
                account = account_.paginate(page=page, per_page=10, error_out=False)
                return render_template('view.html', account=account, logged_in_user=current_user, purchase_form = purchase_form, form = search_form, order = order_by_form, filter_form = filter_form, notification = notification)
            
            elif not article_ac and academic_ac and blogging_ac and price_range_a and price_range_b:
                account_ = Account.query.filter_by(status = 0).filter((Account.account_type == "BLOGGING_ACCOUNT" and "ACADEMIC_WRITING_ACCOUNT")).filter((Account.price >= price_range_a) & (Account.price <= price_range_b))
                account = account_.paginate(page=page, per_page=10, error_out=False)
                return render_template('view.html', account=account, logged_in_user=current_user, purchase_form = purchase_form, form = search_form, order = order_by_form, filter_form = filter_form, notification = notification)

            elif not academic_ac and article_ac and blogging_ac and price_range_a and price_range_b:

src/templates/about_us.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='favicon/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32"  href="{{ url_for('static', filename='favicon/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='favicon/favicon-16x16.png') }}">
    <link rel="manifest" href="{{ url_for('static', filename='favicon/site.webmanifest') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.9.1/font/bootstrap-icons.min.css" integrity="sha512-5PV92qsds/16vyYIJo3T/As4m2d8b6oWYfoqV+vtizRB6KhF1F9kYzWzQmsO6T3z3QG2Xdhrx7FQ+5R1LiQdUA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script> 
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}" >
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/card-styles.css') }}" >

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/about_us.css') }}" >
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script> 
    <title>Document</title>
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-lg navbar-dark navbar-color fixed-top">
          <div class="container-fluid">
            <a class="navbar-brand me-4" href="/">Bush Writers</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <div class="navbar-nav me-auto mb-2 mb-lg-0">
                
                <a class="nav-item nav-link" href="{{ url_for('main.viewpage') }}">Home</a>
                <a class="nav-item nav-link" href="{{ url_for('main.about_us') }}">About Us</a>
                <a class="nav-item nav-link" href="{{ url_for('main.seller') }}">Become A Seller</a>
                <!-- <a class="nav-item nav-link" href="{{ url_for('main.guide') }}">Guide</a> -->
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                {% if not current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('auth.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('auth.register') }}">Register</a>
                {% endif %}
                <a class="nav-item nav-link" href="{{ url_for('main.contact_us') }}">Contact Us</a>
                {% if current_user.is_authenticated %}
                  <a class="nav-item nav-link" href="{{ url_for('main.user_profile', id =current_user.id ) }}">Account</a>
                  <a class="nav-item nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                    {% if current_user.admin %}
                      <a class="nav-item nav-link text-warning" href="/admin">Admin</a>
                    {% endif %}
                    
                {% endif %}
                
                
              {% block navbar %}
                  
              {% endblock navbar %}
                  
                
                
                
                
              </div>
            </div>
          </div>
        </nav>
      </header>
      
      <div class="bg-light">
        <div class="container py-5">
          <div class="row h-100 align-items-center py-5">
            <div class="col-lg-6">
              <h1 class="display-4">About Us</h1>
              <p class="lead text-muted mb-0">We are a marketplace where one can buy and sell feelance accounts at your budget with optimal secured transactions.</p>
              </p>
            </div>
            <div class="col-lg-6 d-none d-lg-block"><img src="https://bootstrapious.com/i/snippets/sn-about/illus.png" alt="" class="img-fluid"></div>
          </div>
        </div>
      </div>
      
      <div class="bg-white py-5">
        <div class="container py-5">
          <div class="row align-items-center mb-5">
            <div class="col-lg-6 order-2 order-lg-1"><i class="fa fa-bar-chart fa-2x mb-3 text-primary"></i>
              <h2 class="font-weight-light">Our Mission</h2>
              <p class="font-italic text-muted mb-4">Our mission is to provide a secured marketplace where anyone can sell or buy freelance accounts at their budget with optimal security of their finance.</p>
            </div>
            <div class="col-lg-5 px-5 mx-auto order-1 order-lg-2"><img src="https://bootstrapious.com/i/snippets/sn-about/img-1.jpg" alt="" class="img-fluid mb-4 mb-lg-0"></div>
          </div>
          <div class="row align-items-center">
            <div class="col-lg-5 px-5 mx-auto"><img src="https://bootstrapious.com/i/snippets/sn-about/img-2.jpg" alt="" class="img-fluid mb-4 mb-lg-0"></div>
            <div class="col-lg-6"><i class="fa fa-leaf fa-2x mb-3 text-primary"></i>
              <h2 class="font-weight-light">Our Goal</h2>
              <p class="font-italic text-muted mb-4">Our objective is to safeguard prospective clients from fraud and fruitless transactions they may encounter when attempting to get a freelancing account. We ensure our customers receive exceptional services and a legitimate account transfer.</p>
              <p class="font-italic text-muted mb-4">We ensure our customers get exemplary service and have a genuine account transfer.</p>
              <a href="#" class="btn btn-light px-5 rounded-pill shadow-sm" data-bs-toggle="modal" data-bs-target="#exampleModal">Learn More</a>
             
            </div>
          </div>
        </div>
      </div>

      <!--TOS Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header bg-dark">
                <h5 class="modal-title text-white" id="exampleModalLabel">Terms Of Service</h5>
                <button type="button" class="text-white btn-close " data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body px-2">
                <ul>
                    <li>One must register to do any transactions within the market place </li>
                    <li> The buyers must do money transaction through the official marketplace accounts using their registered details. If not so, it must be communicated clearly. The buyer must indicate the account ID while doing the verification</li>
                    <li>Transaction will only be complete when the buyer is satisfied with the account. This is when the seller will receive payment and must send other credentials for the account.</li>
                    <li>The seller only send the logins of the account to the buyer for verification.</li>
                    <li>Incase of unmet qualities, the buyer is linked directly to the seller for more account clarification, after which the transaction will be complete or a refund will be initiated.</li>
                    <li>Buyer is given 12hours to reject the account. After receiving all account details and payment is done to the seller, no complains will be accepted.</li>
                    <li>The marketplace is only responsible for the transactions done through the marketplace. Any transaction done outside is at your own risk.</li>
                    <li>The reversal of any fund will constitute a 5% fine + admin fees. </li>
                    <li>f the buyer rejects an account but goes on and change the account details, this will lead to 50-100% fine on the purchase fees.</li>
                    <li>If the seller fails to upload the credentials of the account, this will result to 50-100% fine on the purchased fees.</li>
                </ul>
            </div>
            <div class="modal-footer bg-dark">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
        </div>
    </div>
      
    
      
      <div class="border-top pt-3"></div>
<div class="footer-container">
  <footer class="py-5">
    <div class="row">

      <div class="col-6 col-md-2 mb-3">
        <h5 class="text-white">Get In Touch</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><p class="nav-link p-0 footer-color"><i class="bi bi-geo-alt-fill mr-2"></i>Juja</p></li>
          <li class="nav-item mb-2"><p class="nav-link p-0 footer-color"><i class="bi bi-telephone-fill mr-2"></i>+254743635629</p></li>
          <li class="nav-item mb-2"><p class="nav-link p-0 footer-color"><i class="bi bi-envelope-fill mr-2"></i>bushwriters@gmail.com</p></li>
          <li class="nav-item mb-2"><p class="nav-link p-0 footer-color"><i class="bi bi-whatsapp mr-2"></i>+254743635629</p></li>
          <li class="nav-item mb-2"><p class="nav-link p-0 footer-color"><i class="bi bi-headset mr-2"></i>Customer Support, Sun - Fri, 7AM-10PM</p></li>
        </ul>
      </div>

      <div class="col-6 col-md-2 mb-3">
        <h5 class="text-white">Quick Links</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="{{ url_for('main.viewpage') }}" class="nav-link p-0 footer-color">Home</a></li>
          <li class="nav-item mb-2"><a href="{{ url_for('main.guide') }}" class="nav-link p-0 footer-color">Guide</a></li>
          <li class="nav-item mb-2"><a href="{{ url_for('main.seller') }}" class="nav-link p-0 footer-color">Become A Seller</a></li>
          <li class="nav-item mb-2"><a href="{{ url_for('main.contact_us') }}" class="nav-link p-0 footer-color">Contact Us</a></li>
        </ul>
      </div>

      

      <div class="col-md-5 offset-md-1 mb-3">
        <form>
          <h5 class="text-white">Subscribe to our newsletter</h5>
          <p class="footer-color">Monthly digest of what's new and exciting from us.</p>
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Email Address" aria-label="Recipient's email input" aria-describedby="button-addon4">
            <div class="input-group-append" id="button-addon4">
              <button class="btn btn-primary" type="button">Subscribe</button>
            </div>
          </div>
        </form>
      </div>
    </div>

    <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
      <p class="text-white">&copy; 2022 Company, Inc. All rights reserved.</p>
      <ul class="list-unstyled d-flex">
        <i class="bi bi-twitter p-2 text-white"></i>
        <i class="bi bi-instagram p-2 text-white"></i>
        <i class="bi bi-facebook p-2 text-white"></i>
        <li class="ms-3"><a class="text-white" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"/></svg></a></li>
        <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"/></svg></a></li>
        <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"/></svg></a></li>
      </ul>
    </div>
  </footer>
</div>
  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>

src/templates/login.html
{% extends 'base.html' %}


{% block stylesheets %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}" >
{% endblock stylesheets %}
    

{% block content %}
    <div class="content-section login-form">
        <form action="" method="POST">
            {{ form.csrf_token }}
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4 text-white">Login To Account</legend>

                <!-- Email Field -->
                <div class="form-group">
                    {{ form.email.label(class="form-control-label text-white") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <br/>

                <!-- Password field -->
                <div class="form-group">
                    {{ form.password.label(class="form-control-label text-white") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <br/>

                <!--Remeber Me Feild -->
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label text-white") }}
                </div>
                <br/>

            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-primary") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('auth.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
            <br>
            <div class="border-top pt-3">
                <small class="text-muted text-white">
                    Need An Account? <a class="ml-2" href="{{ url_for('auth.register') }}">Sign Up</a>
                </small>
            </div>
           
        </form>
    </div>
    
{% endblock content %}


{% block footer %}
<div class="border-top pt-3"></div>
<div class="footer-container">
  <footer class="py-5">
    <div class="row">

      <div class="col-6 col-md-2 mb-3">
        <h5 class="text-white">Get In Touch</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><p class="nav-link p-0 footer-color"><i class="bi bi-geo-alt-fill mr-2"></i>Juja</p></li>
          <li class="nav-item mb-2"><p class="nav-link p-0 footer-color"><i class="bi bi-telephone-fill mr-2"></i>+254743635629</p></li>
          <li class="nav-item mb-2"><p class="nav-link p-0 footer-color"><i class="bi bi-envelope-fill mr-2"></i>bushwriters@gmail.com</p></li>
          <li class="nav-item mb-2"><p class="nav-link p-0 footer-color"><i class="bi bi-whatsapp mr-2"></i>+254743635629</p></li>
          <li class="nav-item mb-2"><p class="nav-link p-0 footer-color"><i class="bi bi-headset mr-2"></i>Customer Support, Sun - Fri, 7AM-10PM</p></li>
        </ul>
      </div>

      <div class="col-6 col-md-2 mb-3">
        <h5 class="text-white">Quick Links</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="{{ url_for('main.viewpage') }}" class="nav-link p-0 footer-color">Home</a></li>
          <li class="nav-item mb-2"><a href="{{ url_for('main.guide') }}" class="nav-link p-0 footer-color">Guide</a></li>
          <li class="nav-item mb-2"><a href="{{ url_for('main.seller') }}" class="nav-link p-0 footer-color">Become A Seller</a></li>
          <li class="nav-item mb-2"><a href="{{ url_for('main.contact_us') }}" class="nav-link p-0 footer-color">Contact Us</a></li>
        </ul>
      </div>

      

      <div class="col-md-5 offset-md-1 mb-3">
        <form>
          <h5 class="text-white">Subscribe to our newsletter</h5>
          <p class="footer-color">Monthly digest of what's new and exciting from us.</p>
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Email Address" aria-label="Recipient's email input" aria-describedby="button-addon4">
            <div class="input-group-append" id="button-addon4">
              <button class="btn btn-primary" type="button">Subscribe</button>
            </div>
          </div>
        </form>
      </div>
    </div>

    <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
      <p class="text-white">&copy; 2022 Company, Inc. All rights reserved.</p>
      <ul class="list-unstyled d-flex">
        <i class="bi bi-twitter p-2 text-white"></i>
        <i class="bi bi-instagram p-2 text-white"></i>
        <i class="bi bi-facebook p-2 text-white"></i>
        <li class="ms-3"><a class="text-white" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"/></svg></a></li>
        <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"/></svg></a></li>
        <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"/></svg></a></li>
      </ul>
    </div>
  </footer>
</div>
{% endblock footer %}
    


{% block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
{% endblock scripts %}
    
    